// <auto-generated />
using System;
using ExpenseTrackerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTrackerAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322041923_UpdateCategoriesTable")]
    partial class UpdateCategoriesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTrackerAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#F59E0B",
                            Icon = "🍔",
                            Name = "Food & Dining",
                            Type = "EXPENSE"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#3B82F6",
                            Icon = "🚗",
                            Name = "Transportation",
                            Type = "EXPENSE"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#8B5CF6",
                            Icon = "🏠",
                            Name = "Housing",
                            Type = "EXPENSE"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#EF4444",
                            Icon = "🏥",
                            Name = "Healthcare",
                            Type = "EXPENSE"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#EC4899",
                            Icon = "🎮",
                            Name = "Entertainment",
                            Type = "EXPENSE"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#14B8A6",
                            Icon = "🛍️",
                            Name = "Shopping",
                            Type = "EXPENSE"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#F97316",
                            Icon = "⚡",
                            Name = "Utilities",
                            Type = "EXPENSE"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#6366F1",
                            Icon = "📚",
                            Name = "Education",
                            Type = "EXPENSE"
                        },
                        new
                        {
                            Id = 9,
                            Color = "#10B981",
                            Icon = "💼",
                            Name = "Salary",
                            Type = "INCOME"
                        },
                        new
                        {
                            Id = 10,
                            Color = "#06B6D4",
                            Icon = "💻",
                            Name = "Freelance",
                            Type = "INCOME"
                        },
                        new
                        {
                            Id = 11,
                            Color = "#84CC16",
                            Icon = "📈",
                            Name = "Investments",
                            Type = "INCOME"
                        },
                        new
                        {
                            Id = 12,
                            Color = "#6B7280",
                            Icon = "📦",
                            Name = "Other",
                            Type = "EXPENSE"
                        });
                });

            modelBuilder.Entity("ExpenseTrackerAPI.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ExpenseTrackerAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExpenseTrackerAPI.Models.Category", b =>
                {
                    b.HasOne("ExpenseTrackerAPI.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseTrackerAPI.Models.Transaction", b =>
                {
                    b.HasOne("ExpenseTrackerAPI.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseTrackerAPI.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseTrackerAPI.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ExpenseTrackerAPI.Models.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
